 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posProjectForTuring.ui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import posProjectForTuring.controller.PasswordHashing;
import posProjectForTuring.model.Admin;
import posProjectForTuring.model.service.AdminService;
import posProjectForTuring.model.service.impl.AdminServiceImpl;

/**
 *
 * @author hp
 */
public class AdminAccountRegistration extends javax.swing.JFrame {

    public AdminAccountRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreateAccount = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblShowOrHide = new javax.swing.JLabel();
        lblPasswordConfirm = new javax.swing.JLabel();
        pwdPasswordConfirm = new javax.swing.JPasswordField();
        lblShowOrHide1 = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(500, 200));

        lblCreateAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCreateAccount.setText("Create a new Admin account");

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        lblName.setText("Name");

        lblUsername.setText("Username");

        lblPassword.setText("Password");

        lblShowOrHide.setIcon(new javax.swing.ImageIcon("E:\\Turing Course\\PosProjectForTuring\\images\\ShowPassword.png")); // NOI18N
        lblShowOrHide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShowOrHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowOrHideMouseClicked(evt);
            }
        });

        lblPasswordConfirm.setText("Confirm Password");

        lblShowOrHide1.setIcon(new javax.swing.ImageIcon("E:\\Turing Course\\PosProjectForTuring\\images\\ShowPassword.png")); // NOI18N
        lblShowOrHide1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShowOrHide1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowOrHide1MouseClicked(evt);
            }
        });

        lblPhoneNo.setText("Phone No");

        lblAddress.setText("Address");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(lblCreateAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblUsername)
                                    .addComponent(lblPassword))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblPasswordConfirm)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pwdPassword)
                            .addComponent(txtName)
                            .addComponent(txtUsername)
                            .addComponent(pwdPasswordConfirm)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNo)
                            .addComponent(lblAddress))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSignUp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(btnCancel))
                            .addComponent(txtPhoneNo)
                            .addComponent(txtAddress))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblShowOrHide))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblShowOrHide1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCreateAccount)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword)))
                    .addComponent(lblShowOrHide))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pwdPasswordConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPasswordConfirm))
                    .addComponent(lblShowOrHide1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNo)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    AdminService adminService = new AdminServiceImpl();
    
    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        Admin admin = new Admin();
        PasswordHashing passwordHashing = new PasswordHashing();
        
        if(isPerfect() && isPasswordConfirm()){
            admin.setName(this.txtName.getText());
            admin.setUsername(this.txtUsername.getText());
            admin.setPassword(passwordHashing.hash(this.pwdPassword.getText()));
            admin.setPhoneNo(this.txtPhoneNo.getText());
            admin.setAddress(this.txtAddress.getText());
            
            //adminService.insertAdmin(admin);

            JOptionPane.showMessageDialog(null, "Account successfully created!", "Sign Up Done!", INFORMATION_MESSAGE);
            this.dispose();
            MainLogin.disposeMainLogin();
            java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                        if ("Metal".equals(info.getName())) {
                            javax.swing.UIManager.setLookAndFeel(info.getClassName());
                            break;
                        }
                    }
                } catch (Exception e){
                    e.printStackTrace();
                }
                new MainLogin().setVisible(true);
            }
        });
        }
        else{
            if(!isPerfect()){
                JOptionPane.showMessageDialog(null, "All fields must be filled!", "Fields cannot be null!", WARNING_MESSAGE);
            }
            
            else{
                JOptionPane.showMessageDialog(null, "Passwords must be matched!", "Passwords Do Not Match!", WARNING_MESSAGE);
                this.pwdPassword.setText("");
                this.pwdPasswordConfirm.setText("");
            }
        }
    }//GEN-LAST:event_btnSignUpActionPerformed
    boolean isShow = true;
    private void lblShowOrHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowOrHideMouseClicked
        if(isShow){
            this.lblShowOrHide.setIcon(new ImageIcon("E:\\Turing Course\\PosProjectForTuring\\images\\HidePassword.png"));
            isShow = false;
            this.pwdPassword.setEchoChar((char)0);
        }
        else{
            this.lblShowOrHide.setIcon(new ImageIcon("E:\\Turing Course\\PosProjectForTuring\\images\\ShowPassword.png"));
            isShow = true;
            this.pwdPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_lblShowOrHideMouseClicked

    boolean isShow1 = true;
    private void lblShowOrHide1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowOrHide1MouseClicked
        if(isShow1){
            this.lblShowOrHide1.setIcon(new ImageIcon("E:\\Turing Course\\PosProjectForTuring\\images\\HidePassword.png"));
            isShow1 = false;
            this.pwdPasswordConfirm.setEchoChar((char)0);
        }
        else{
            this.lblShowOrHide1.setIcon(new ImageIcon("E:\\Turing Course\\PosProjectForTuring\\images\\ShowPassword.png"));
            isShow1 = true;
            this.pwdPasswordConfirm.setEchoChar('•');
        }
    }//GEN-LAST:event_lblShowOrHide1MouseClicked

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    
    private boolean isPerfect(){
        if(this.txtName.getText().isEmpty()){
            return false;
        }
        else if(this.txtUsername.getText().isEmpty()){
            return false;
        }
        else if(this.pwdPassword.getText().isEmpty()){
            return false;
        }
        else if(this.pwdPasswordConfirm.getText().isEmpty()){
            return false;
        }
        else if(this.txtPhoneNo.getText().isEmpty()){
            return false;
        }
        else if(this.txtAddress.getText().isEmpty()){
            return false;
        }
        else{
           return true; 
        }
    }
    
    private boolean isPasswordConfirm(){
        if(this.pwdPassword.getText().equals(this.pwdPasswordConfirm.getText())){
            return true;
        }
        else{
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPasswordConfirm;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblShowOrHide;
    private javax.swing.JLabel lblShowOrHide1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField pwdPasswordConfirm;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
