/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package posProjectForTuring.ui.panelsForAdminPage;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import posProjectForTuring.ui.AdminPage;

/**
 *
 * @author hp
 */
public class ControlPanel extends javax.swing.JPanel {
    
    public ControlPanel() {
        initComponents();
        addHoverEffect();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProductData = new javax.swing.JButton();
        btnProductCrud = new javax.swing.JButton();
        btnSaleReports = new javax.swing.JButton();
        btnCashierCrud = new javax.swing.JButton();
        btnCashierData = new javax.swing.JButton();

        setBackground(java.awt.Color.decode("#263238"));

        btnProductData.setBackground(java.awt.Color.decode("#263238"));
        btnProductData.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnProductData.setForeground(new java.awt.Color(240, 240, 240));
        btnProductData.setText("Product Data");
        btnProductData.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnProductData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductData.setFocusPainted(false);
        btnProductData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductDataActionPerformed(evt);
            }
        });

        btnProductCrud.setBackground(java.awt.Color.decode("#263238"));
        btnProductCrud.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnProductCrud.setForeground(new java.awt.Color(240, 240, 240));
        btnProductCrud.setText("Product CRUD");
        btnProductCrud.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnProductCrud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProductCrud.setFocusPainted(false);
        btnProductCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductCrudActionPerformed(evt);
            }
        });

        btnSaleReports.setBackground(java.awt.Color.decode("#263238"));
        btnSaleReports.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnSaleReports.setForeground(new java.awt.Color(240, 240, 240));
        btnSaleReports.setText("Sale Reports");
        btnSaleReports.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnSaleReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaleReports.setFocusPainted(false);
        btnSaleReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleReportsActionPerformed(evt);
            }
        });

        btnCashierCrud.setBackground(java.awt.Color.decode("#263238"));
        btnCashierCrud.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnCashierCrud.setForeground(new java.awt.Color(240, 240, 240));
        btnCashierCrud.setText("Cashier CRUD");
        btnCashierCrud.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnCashierCrud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCashierCrud.setFocusPainted(false);
        btnCashierCrud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierCrudActionPerformed(evt);
            }
        });

        btnCashierData.setBackground(java.awt.Color.decode("#263238"));
        btnCashierData.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        btnCashierData.setForeground(new java.awt.Color(240, 240, 240));
        btnCashierData.setText("Cashier Data");
        btnCashierData.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnCashierData.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCashierData.setFocusPainted(false);
        btnCashierData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCashierDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnProductData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnProductCrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(btnSaleReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addComponent(btnCashierCrud, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCashierData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btnCashierData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnCashierCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProductData, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnProductCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSaleReports, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(566, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    public void modifyFocusedButtonDesign(AbstractButton focusedButton){
        focusedButton.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 20));
        focusedButton.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 10, Color.white));
        
        for(Component component : this.getComponents()){
            if(component instanceof AbstractButton && component!= focusedButton){
                component.setFont(new java.awt.Font("Arial", java.awt.Font.PLAIN, 13));
                ((AbstractButton)component).setBorder(BorderFactory.createEmptyBorder());
            }
        }        
    }
    
    public void hoverEffect(AbstractButton hoveredButton){
        hoveredButton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                hoveredButton.setBackground(Color.decode("#455A64"));
                hoveredButton.setForeground(Color.black);
            }

            @Override
            public void mouseExited(MouseEvent e) {
                hoveredButton.setBackground(java.awt.Color.decode("#263238"));
                hoveredButton.setForeground(Color.white);
            }
        });
    }
    
    public void addHoverEffect(){
        for(Component component : this.getComponents()){
            if(component instanceof AbstractButton){
                hoverEffect((AbstractButton) component);
            }
        }
    }
    
    public void setSelectedPanelVisible(javax.swing.JPanel selectedPanel){
        List<javax.swing.JPanel> panels = new ArrayList<javax.swing.JPanel>();
        panels.add(AdminPage.productData);
        panels.add(AdminPage.productCrud);
        
        panels.remove(selectedPanel);
        
        selectedPanel.setVisible(true);
        for(javax.swing.JPanel panel: panels){
            panel.setVisible(false);
        }
    }
    
    private void btnProductDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductDataActionPerformed
        modifyFocusedButtonDesign(this.btnProductData);
        setSelectedPanelVisible(AdminPage.productData);
    }//GEN-LAST:event_btnProductDataActionPerformed

    private void btnProductCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductCrudActionPerformed
        modifyFocusedButtonDesign(this.btnProductCrud);
        setSelectedPanelVisible(AdminPage.productCrud);
    }//GEN-LAST:event_btnProductCrudActionPerformed

    private void btnSaleReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleReportsActionPerformed
        modifyFocusedButtonDesign(this.btnSaleReports);
    }//GEN-LAST:event_btnSaleReportsActionPerformed

    private void btnCashierCrudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierCrudActionPerformed
        modifyFocusedButtonDesign(this.btnCashierCrud);
    }//GEN-LAST:event_btnCashierCrudActionPerformed

    private void btnCashierDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCashierDataActionPerformed
        modifyFocusedButtonDesign(this.btnCashierData);
    }//GEN-LAST:event_btnCashierDataActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCashierCrud;
    private javax.swing.JButton btnCashierData;
    private javax.swing.JButton btnProductCrud;
    private javax.swing.JButton btnProductData;
    private javax.swing.JButton btnSaleReports;
    // End of variables declaration//GEN-END:variables
}
